frontend:
  image:
    repository: your-dockerhub-username/frontend
    tag: latest
  replicaCount: 2
  service:
    type: ClusterIP
    port: 3000

backend:
  image:
    repository: your-dockerhub-username/backend
    tag: latest
  replicaCount: 2
  service:
    type: ClusterIP
    port: 5000
